export const BASE_TRACK_HEIGHT = 82;
export const SCROLLBAR_OFFSET = 16;
export const TRACK_PANEL_COLLAPSED_WIDTH = 38;
export const TRACK_PANEL_EXPANDED_WIDTH = 256;
export const TOOLBAR_HEIGHT = 72;
