import { KeyData } from "@/pages/studio/audio-engine/components/keyboard";

export const keys: KeyData[] = [
  {
    type: "white",
    keyboardKey: "z",
    note: "C",
    relativeOctave: 0,
  },
  {
    type: "black",
    keyboardKey: "s",
    note: "Db",
    relativeOctave: 0,
  },
  {
    type: "white",
    keyboardKey: "x",
    note: "D",
    relativeOctave: 0,
  },
  {
    type: "black",
    keyboardKey: "d",
    note: "Eb",
    relativeOctave: 0,
  },
  {
    type: "white",
    keyboardKey: "c",
    note: "E",
    relativeOctave: 0,
  },
  {
    type: "white",
    keyboardKey: "v",
    note: "F",
    relativeOctave: 0,
  },
  {
    type: "black",
    keyboardKey: "g",
    note: "Gb",
    relativeOctave: 0,
  },
  {
    type: "white",
    keyboardKey: "b",
    note: "G",
    relativeOctave: 0,
  },
  {
    type: "black",
    keyboardKey: "h",
    note: "Ab",
    relativeOctave: 0,
  },
  {
    type: "white",
    keyboardKey: "n",
    note: "A",
    relativeOctave: 0,
  },
  {
    type: "black",
    keyboardKey: "j",
    note: "Bb",
    relativeOctave: 0,
  },
  {
    type: "white",
    keyboardKey: "m",
    note: "B",
    relativeOctave: 0,
  },

  {
    type: "white",
    keyboardKey: "q",
    note: "C",
    relativeOctave: 1,
  },
  {
    type: "black",
    keyboardKey: "2",
    note: "Db",
    relativeOctave: 1,
  },
  {
    type: "white",
    keyboardKey: "w",
    note: "D",
    relativeOctave: 1,
  },
  {
    type: "black",
    keyboardKey: "3",
    note: "Eb",
    relativeOctave: 1,
  },
  {
    type: "white",
    keyboardKey: "e",
    note: "E",
    relativeOctave: 1,
  },
  {
    type: "white",
    keyboardKey: "r",
    note: "F",
    relativeOctave: 1,
  },
  {
    type: "black",
    keyboardKey: "5",
    note: "Gb",
    relativeOctave: 1,
  },
  {
    type: "white",
    keyboardKey: "t",
    note: "G",
    relativeOctave: 1,
  },
  {
    type: "black",
    keyboardKey: "6",
    note: "Ab",
    relativeOctave: 1,
  },
  {
    type: "white",
    keyboardKey: "y",
    note: "A",
    relativeOctave: 1,
  },
  {
    type: "black",
    keyboardKey: "7",
    note: "Bb",
    relativeOctave: 1,
  },
  {
    type: "white",
    keyboardKey: "u",
    note: "B",
    relativeOctave: 1,
  },
  {
    type: "white",
    keyboardKey: "i",
    note: "C",
    relativeOctave: 2,
  },
  {
    type: "black",
    keyboardKey: "9",
    note: "Db",
    relativeOctave: 2,
  },
  {
    type: "white",
    keyboardKey: "o",
    note: "D",
    relativeOctave: 2,
  },
  {
    type: "black",
    keyboardKey: "0",
    note: "Eb",
    relativeOctave: 2,
  },
  {
    type: "white",
    keyboardKey: "p",
    note: "E",
    relativeOctave: 2,
  },
];
